language: python

python:
  - "2.7"

install:
  - pip install tox --use-mirrors
  - pip install coveralls

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy

script:
  - tox -e $TOXENV
  - coverage run --source=ebay setup.py test

after_success:
  - coveralls